#+TITLE: Report from PeerSim simulations
#+AUTHOR: Dan Rachou (danra), Srinivas Krishna (srinivk), Nemanja Lakicevic (nemanjla)
#+OPTIONS: toc:nil
#+LATEX: \newpage


*  Which topology do you think is better to bootstrap such a P2P system?

  The simulation finishes a lot quicker when we have bootstrapped the ring topology to it.  To the
  programmer executing the code, it is of course nicer to wait less for the results, but our
  assumption tells us that "better" has nothing to do time running the simulation.  We think it
  refers to the validation of the desired properties.

  When bootstrapping the star topology, the simulation starts with every node linking to the same
  node.  The center node does not have any out links, forcing the neighbor exchange to start from
  the center node, leading the node to immediately be overloaded with shuffle requests from the
  other nodes.  In the worst case, this single node has to reject 9999 shuffle requests before it
  receives shuffle reply and can update its cache.  Since there is a center node, the average path
  length less than two.  In the ring topology, every node has one out link and there is a
  communication path between every node.  The longest path between two nodes are 9999 hops, and the
  shortest is 1 hop.  The star topology begins with an average length shorter than the baseline and
  hits the baseline a lot quicker than the ring topology, while the ring topology begins with an
  average length much longer than the baselines.

  We can see from the graphs representing the average clustering coefficient that bootstrapping with
  the star topology, the overlay network reaches baselines of a random graph after fewer cycles than
  when it it bootstrapped with the ring topology.  Bootstrapping the star topology to this P2P system results in reaching the baselines earlier in both properties, which is to prefer, and therefore "better".
  
* What is the importance of the cache size?
  
  There are tradeoffs between the two cache sizes.  The average path length in the overlay network
  is less when the cache size is 50, however, the cluster coefficient hits a stable baseline after
  more cycles have passed, and the baseline is also higher compared to when the cache size is 30.
  The degree distribution is also less when the cache size is 50.

  To summarize, a cache size of 50 nodes results in an overlay network that has slightly lower
  communication costs and transfer speeds, but at a higher risk of network partitioning and higher
  number of redundant message deliveries.  The network is also less distributed, moving it closer to
  a decentralized network instead of a distributed one.
